using System.Collections;
using System.Collections.Generic;
using UnityEngine;


[RequireComponent(typeof(MeshFilter))]
[RequireComponent(typeof(MeshRenderer))]

[ExecuteInEditMode]
public class TriangleScript : MonoBehaviour
{

    [Header("Enabler")]
    [SerializeField]
    private bool genTriangle = false;

    [SerializeField]
    private Vector3 size = Vector3.one;

    private List<Material> materialList;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void OnValidate()
    {
        if (genTriangle)
        {
            GenerateTriangle();
        }
    }

    private void GenerateTriangle() 
    {

        //1. initialise mesh filter
        MeshFilter meshFilter = this.GetComponent<MeshFilter>();

        //2. initialise mesh builder
        MeshGenerator meshGenerator = new MeshGenerator(1);

        //3. build our triangle

        Vector3 p0 = new Vector3(size.x, size.y, -size.z);
        Vector3 p1 = new Vector3(-size.x, size.y, -size.z);
        Vector3 p2 = new Vector3(-size.x, size.y, size.z);

        meshGenerator.BuildTriangle(p0, p1, p2, 0);

        //4. mesh filter's mesh to the one generated by the mesh builder
        meshFilter.mesh = meshGenerator.CreateMesh();

        //5. initialise mesh renderer and assign material list to the mesh renderer's materials list
        MeshRenderer meshRenderer = this.GetComponent<MeshRenderer>();
        AddMaterials();
        meshRenderer.materials = materialList.ToArray();
        
    }


    private void AddMaterials()
    {
        Material greenMat = new Material(Shader.Find("Specular"));
        greenMat.color = Color.green;

        materialList = new List<Material>();
        materialList.Add(greenMat);
    }

}
